// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: internal/api/proto/devops.proto

package devops

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Devops_Ping_FullMethodName = "/api.Devops/Ping"
)

// DevopsClient is the client API for Devops service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevopsClient interface {
	//  rpc GetMetric(GetMetricRequest) returns (GetMetricResponse) {}
	//  rpc CreateMetric(CreateMetricRequest) returns (CreateMetricResponse) {}
	//  rpc CreateMetrics(CreateMetricsRequest) returns (CreateMetricsResponse) {}
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type devopsClient struct {
	cc grpc.ClientConnInterface
}

func NewDevopsClient(cc grpc.ClientConnInterface) DevopsClient {
	return &devopsClient{cc}
}

func (c *devopsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Devops_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevopsServer is the server API for Devops service.
// All implementations must embed UnimplementedDevopsServer
// for forward compatibility
type DevopsServer interface {
	//  rpc GetMetric(GetMetricRequest) returns (GetMetricResponse) {}
	//  rpc CreateMetric(CreateMetricRequest) returns (CreateMetricResponse) {}
	//  rpc CreateMetrics(CreateMetricsRequest) returns (CreateMetricsResponse) {}
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedDevopsServer()
}

// UnimplementedDevopsServer must be embedded to have forward compatible implementations.
type UnimplementedDevopsServer struct {
}

func (UnimplementedDevopsServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDevopsServer) mustEmbedUnimplementedDevopsServer() {}

// UnsafeDevopsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevopsServer will
// result in compilation errors.
type UnsafeDevopsServer interface {
	mustEmbedUnimplementedDevopsServer()
}

func RegisterDevopsServer(s grpc.ServiceRegistrar, srv DevopsServer) {
	s.RegisterService(&Devops_ServiceDesc, srv)
}

func _Devops_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devops_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Devops_ServiceDesc is the grpc.ServiceDesc for Devops service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Devops_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Devops",
	HandlerType: (*DevopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Devops_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/proto/devops.proto",
}
