// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: internal/api/proto/devops.proto

package devops

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Devops_GetMetric_FullMethodName     = "/api.Devops/GetMetric"
	Devops_CreateMetric_FullMethodName  = "/api.Devops/CreateMetric"
	Devops_CreateMetrics_FullMethodName = "/api.Devops/CreateMetrics"
	Devops_Ping_FullMethodName          = "/api.Devops/Ping"
)

// DevopsClient is the client API for Devops service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevopsClient interface {
	GetMetric(ctx context.Context, in *GetMetricRequest, opts ...grpc.CallOption) (*GetMetricResponse, error)
	CreateMetric(ctx context.Context, in *CreateMetricRequest, opts ...grpc.CallOption) (*CreateMetricResponse, error)
	CreateMetrics(ctx context.Context, in *CreateMetricsRequest, opts ...grpc.CallOption) (*CreateMetricsResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type devopsClient struct {
	cc grpc.ClientConnInterface
}

func NewDevopsClient(cc grpc.ClientConnInterface) DevopsClient {
	return &devopsClient{cc}
}

func (c *devopsClient) GetMetric(ctx context.Context, in *GetMetricRequest, opts ...grpc.CallOption) (*GetMetricResponse, error) {
	out := new(GetMetricResponse)
	err := c.cc.Invoke(ctx, Devops_GetMetric_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) CreateMetric(ctx context.Context, in *CreateMetricRequest, opts ...grpc.CallOption) (*CreateMetricResponse, error) {
	out := new(CreateMetricResponse)
	err := c.cc.Invoke(ctx, Devops_CreateMetric_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) CreateMetrics(ctx context.Context, in *CreateMetricsRequest, opts ...grpc.CallOption) (*CreateMetricsResponse, error) {
	out := new(CreateMetricsResponse)
	err := c.cc.Invoke(ctx, Devops_CreateMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Devops_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevopsServer is the server API for Devops service.
// All implementations must embed UnimplementedDevopsServer
// for forward compatibility
type DevopsServer interface {
	GetMetric(context.Context, *GetMetricRequest) (*GetMetricResponse, error)
	CreateMetric(context.Context, *CreateMetricRequest) (*CreateMetricResponse, error)
	CreateMetrics(context.Context, *CreateMetricsRequest) (*CreateMetricsResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedDevopsServer()
}

// UnimplementedDevopsServer must be embedded to have forward compatible implementations.
type UnimplementedDevopsServer struct {
}

func (UnimplementedDevopsServer) GetMetric(context.Context, *GetMetricRequest) (*GetMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetric not implemented")
}
func (UnimplementedDevopsServer) CreateMetric(context.Context, *CreateMetricRequest) (*CreateMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMetric not implemented")
}
func (UnimplementedDevopsServer) CreateMetrics(context.Context, *CreateMetricsRequest) (*CreateMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMetrics not implemented")
}
func (UnimplementedDevopsServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDevopsServer) mustEmbedUnimplementedDevopsServer() {}

// UnsafeDevopsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevopsServer will
// result in compilation errors.
type UnsafeDevopsServer interface {
	mustEmbedUnimplementedDevopsServer()
}

func RegisterDevopsServer(s grpc.ServiceRegistrar, srv DevopsServer) {
	s.RegisterService(&Devops_ServiceDesc, srv)
}

func _Devops_GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).GetMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devops_GetMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).GetMetric(ctx, req.(*GetMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_CreateMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).CreateMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devops_CreateMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).CreateMetric(ctx, req.(*CreateMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_CreateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).CreateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devops_CreateMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).CreateMetrics(ctx, req.(*CreateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devops_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Devops_ServiceDesc is the grpc.ServiceDesc for Devops service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Devops_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Devops",
	HandlerType: (*DevopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetric",
			Handler:    _Devops_GetMetric_Handler,
		},
		{
			MethodName: "CreateMetric",
			Handler:    _Devops_CreateMetric_Handler,
		},
		{
			MethodName: "CreateMetrics",
			Handler:    _Devops_CreateMetrics_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Devops_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/proto/devops.proto",
}
